FROM kserve/sklearnserver:v0.15.0

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Instalar versiones específicas
RUN pip install --no-cache-dir \
    numpy==1.26.4 \
    scikit-learn==1.2.2 \
    pandas==2.3.2 \
    scipy==1.11.4

# (Opcional) Añadir utilidades si las necesitas
RUN pip install --no-cache-dir joblib

# No cambiar el entrypoint del runtime
