apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: ns-test-model
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
